// Static Mercari shipping class data — fallback when the live API is unavailable.
// Weights in ounces, packageSize in cubic inches (L×W×H), fees in cents.

interface ShippingClass {
  id: number;
  name: string;
  carrier: string;
  handlingType: string;
  carrierDisplayName: string;
  requestClassDisplayName: string;
  minWeight: number;
  maxWeight: number;
  packageSize: number;
  fee: number;
  etaForSeller: string;
  requiresDimensions: boolean;
}

const shippingCarriers: ShippingClass[] = [
  { id: 2288, name: "0.25 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 0, maxWeight: 4, packageSize: 3456, fee: 1795, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2289, name: "0.5 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 5, maxWeight: 8, packageSize: 3456, fee: 1795, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2290, name: "1 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 9, maxWeight: 16, packageSize: 3456, fee: 1795, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2291, name: "2 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 17, maxWeight: 32, packageSize: 3456, fee: 1795, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2292, name: "3 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 33, maxWeight: 48, packageSize: 3456, fee: 1795, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2293, name: "4 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 49, maxWeight: 64, packageSize: 3456, fee: 1795, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2294, name: "5 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 65, maxWeight: 80, packageSize: 3456, fee: 1895, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2295, name: "6 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 81, maxWeight: 96, packageSize: 3456, fee: 1995, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2296, name: "7 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 97, maxWeight: 112, packageSize: 3456, fee: 2095, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2297, name: "8 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 113, maxWeight: 128, packageSize: 3456, fee: 2195, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2298, name: "9 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 129, maxWeight: 144, packageSize: 3456, fee: 2295, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2299, name: "10 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 145, maxWeight: 160, packageSize: 3456, fee: 2395, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2300, name: "11 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 161, maxWeight: 176, packageSize: 3456, fee: 2495, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2301, name: "12 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 177, maxWeight: 192, packageSize: 3456, fee: 2595, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2302, name: "13 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 193, maxWeight: 208, packageSize: 3456, fee: 2695, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2303, name: "14 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 209, maxWeight: 224, packageSize: 3456, fee: 3200, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2304, name: "15 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 225, maxWeight: 240, packageSize: 3456, fee: 3300, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2305, name: "16 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 241, maxWeight: 256, packageSize: 3456, fee: 3400, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2306, name: "17 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 257, maxWeight: 272, packageSize: 3456, fee: 3500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2307, name: "18 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 273, maxWeight: 288, packageSize: 3672, fee: 3600, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2308, name: "19 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 289, maxWeight: 304, packageSize: 3825, fee: 3800, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2309, name: "20 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 305, maxWeight: 320, packageSize: 3978, fee: 4200, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2310, name: "30 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 321, maxWeight: 480, packageSize: 5928, fee: 5500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2311, name: "40 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 481, maxWeight: 640, packageSize: 7980, fee: 9500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2312, name: "50 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 641, maxWeight: 800, packageSize: 10013, fee: 14000, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2318, name: "0.25 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 0, maxWeight: 4, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2319, name: "0.5 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 5, maxWeight: 8, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2320, name: "1 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 9, maxWeight: 16, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2321, name: "2 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 17, maxWeight: 32, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2322, name: "3 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 33, maxWeight: 48, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2323, name: "4 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 49, maxWeight: 64, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2324, name: "5 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 65, maxWeight: 80, packageSize: 3456, fee: 1099, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2325, name: "1 lb", carrier: "shippo_usps", handlingType: "media_mail", carrierDisplayName: "USPS Media Mail", requestClassDisplayName: "USPS Media Mail", minWeight: 0, maxWeight: 16, packageSize: 1728, fee: 499, etaForSeller: "2 - 10 days", requiresDimensions: true },
  { id: 2326, name: "2 lb", carrier: "shippo_usps", handlingType: "media_mail", carrierDisplayName: "USPS Media Mail", requestClassDisplayName: "USPS Media Mail", minWeight: 17, maxWeight: 32, packageSize: 1728, fee: 599, etaForSeller: "2 - 10 days", requiresDimensions: true },
  { id: 2327, name: "3 lb", carrier: "shippo_usps", handlingType: "media_mail", carrierDisplayName: "USPS Media Mail", requestClassDisplayName: "USPS Media Mail", minWeight: 33, maxWeight: 48, packageSize: 1728, fee: 699, etaForSeller: "2 - 10 days", requiresDimensions: true },
  { id: 2331, name: "0.25 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 0, maxWeight: 4, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2332, name: "0.5 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 5, maxWeight: 8, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2333, name: "1 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 9, maxWeight: 16, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2334, name: "2 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 17, maxWeight: 32, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2335, name: "3 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 33, maxWeight: 48, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2336, name: "4 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 49, maxWeight: 64, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2337, name: "5 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 65, maxWeight: 80, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2338, name: "6 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 81, maxWeight: 96, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2339, name: "7 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 97, maxWeight: 112, packageSize: 3456, fee: 2500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2340, name: "8 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 113, maxWeight: 128, packageSize: 3456, fee: 2600, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2341, name: "9 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 129, maxWeight: 144, packageSize: 3456, fee: 2700, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2342, name: "10 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 145, maxWeight: 160, packageSize: 3456, fee: 2800, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2343, name: "11 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 161, maxWeight: 176, packageSize: 3456, fee: 2900, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2344, name: "12 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 177, maxWeight: 192, packageSize: 3456, fee: 3000, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2345, name: "13 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 193, maxWeight: 208, packageSize: 3456, fee: 3100, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2346, name: "14 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 209, maxWeight: 224, packageSize: 3456, fee: 3250, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2347, name: "15 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 225, maxWeight: 240, packageSize: 3456, fee: 3350, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2348, name: "16 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 241, maxWeight: 256, packageSize: 3456, fee: 3350, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2349, name: "17 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 257, maxWeight: 272, packageSize: 3456, fee: 3450, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2350, name: "18 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 273, maxWeight: 288, packageSize: 3456, fee: 3550, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2351, name: "19 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 289, maxWeight: 304, packageSize: 3519, fee: 3650, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2352, name: "20 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 305, maxWeight: 320, packageSize: 3672, fee: 4200, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2353, name: "30 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 321, maxWeight: 480, packageSize: 5616, fee: 7000, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2354, name: "40 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 481, maxWeight: 640, packageSize: 7448, fee: 9500, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2355, name: "50 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 641, maxWeight: 800, packageSize: 9367, fee: 16000, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2361, name: "0.25 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 0, maxWeight: 4, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2362, name: "0.5 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 5, maxWeight: 8, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2363, name: "1 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 9, maxWeight: 16, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2364, name: "2 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 17, maxWeight: 32, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2365, name: "3 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 33, maxWeight: 48, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2366, name: "4 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 49, maxWeight: 64, packageSize: 3456, fee: 999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2367, name: "5 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 65, maxWeight: 80, packageSize: 3456, fee: 1299, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2368, name: "6 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 81, maxWeight: 96, packageSize: 3456, fee: 1700, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2369, name: "7 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 97, maxWeight: 112, packageSize: 3456, fee: 1800, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2370, name: "8 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 113, maxWeight: 128, packageSize: 3456, fee: 1900, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2371, name: "9 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 129, maxWeight: 144, packageSize: 3456, fee: 1999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2372, name: "10 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 145, maxWeight: 160, packageSize: 3456, fee: 1999, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2415, name: "0.25 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 0, maxWeight: 4, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2416, name: "0.5 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 5, maxWeight: 8, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2417, name: "1 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 9, maxWeight: 16, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2418, name: "2 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 17, maxWeight: 32, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2419, name: "3 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 33, maxWeight: 48, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2420, name: "4 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 49, maxWeight: 64, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2421, name: "5 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 65, maxWeight: 80, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2422, name: "6 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 81, maxWeight: 96, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2423, name: "7 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 97, maxWeight: 112, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2424, name: "8 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 113, maxWeight: 128, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2425, name: "9 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 129, maxWeight: 144, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2426, name: "10 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 145, maxWeight: 160, packageSize: 1728, fee: 1199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2427, name: "11 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 161, maxWeight: 176, packageSize: 1728, fee: 1399, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2428, name: "12 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 177, maxWeight: 192, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2429, name: "13 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 193, maxWeight: 208, packageSize: 1728, fee: 1799, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2430, name: "14 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 209, maxWeight: 224, packageSize: 1728, fee: 1999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2431, name: "15 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 225, maxWeight: 240, packageSize: 1728, fee: 2199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2432, name: "16 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 241, maxWeight: 256, packageSize: 1728, fee: 2399, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2433, name: "17 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 257, maxWeight: 272, packageSize: 1728, fee: 2599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2434, name: "18 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 273, maxWeight: 288, packageSize: 1728, fee: 2799, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2435, name: "19 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 289, maxWeight: 304, packageSize: 1728, fee: 2999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2436, name: "20 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 305, maxWeight: 320, packageSize: 1728, fee: 3499, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2437, name: "30 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 321, maxWeight: 480, packageSize: 1728, fee: 3999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2438, name: "40 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 481, maxWeight: 640, packageSize: 1728, fee: 4499, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2439, name: "50 lb", carrier: "ups", handlingType: "standard", carrierDisplayName: "UPS Ground", requestClassDisplayName: "UPS Ground", minWeight: 641, maxWeight: 800, packageSize: 1728, fee: 4999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2445, name: "0.25 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 0, maxWeight: 4, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2446, name: "0.5 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 5, maxWeight: 8, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2447, name: "1 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 9, maxWeight: 16, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2448, name: "2 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 17, maxWeight: 32, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2449, name: "3 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 33, maxWeight: 48, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2450, name: "4 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 49, maxWeight: 64, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2451, name: "5 lb", carrier: "ups", handlingType: "surepost", carrierDisplayName: "UPS Ground Saver", requestClassDisplayName: "UPS Ground Saver", minWeight: 65, maxWeight: 80, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2452, name: "0.25 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 0, maxWeight: 4, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2453, name: "0.5 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 5, maxWeight: 8, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2454, name: "1 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 9, maxWeight: 16, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2455, name: "2 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 17, maxWeight: 32, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2456, name: "3 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 33, maxWeight: 48, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2457, name: "4 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 49, maxWeight: 64, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2458, name: "5 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 65, maxWeight: 80, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2459, name: "6 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 81, maxWeight: 96, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2460, name: "7 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 97, maxWeight: 112, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2461, name: "8 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 113, maxWeight: 128, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2462, name: "9 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 129, maxWeight: 144, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2463, name: "10 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 145, maxWeight: 160, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2464, name: "11 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 161, maxWeight: 176, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2465, name: "12 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 177, maxWeight: 192, packageSize: 1728, fee: 1599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2466, name: "13 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 193, maxWeight: 208, packageSize: 1728, fee: 1799, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2467, name: "14 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 209, maxWeight: 224, packageSize: 1728, fee: 1999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2468, name: "15 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 225, maxWeight: 240, packageSize: 1728, fee: 2199, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2469, name: "16 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 241, maxWeight: 256, packageSize: 1728, fee: 2399, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2470, name: "17 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 257, maxWeight: 272, packageSize: 1728, fee: 2599, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2471, name: "18 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 273, maxWeight: 288, packageSize: 1728, fee: 2799, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2472, name: "19 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 289, maxWeight: 304, packageSize: 1728, fee: 2999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2473, name: "20 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 305, maxWeight: 320, packageSize: 1728, fee: 3499, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2474, name: "30 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 321, maxWeight: 480, packageSize: 1728, fee: 3999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2475, name: "40 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 481, maxWeight: 640, packageSize: 1728, fee: 4499, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2476, name: "50 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "FedEx Home", requestClassDisplayName: "FedEx Home", minWeight: 641, maxWeight: 800, packageSize: 1728, fee: 4999, etaForSeller: "1 - 6 days", requiresDimensions: true },
  { id: 2479, name: "80 lb", carrier: "fedex", handlingType: "standard", carrierDisplayName: "Ground", requestClassDisplayName: "Ground", minWeight: 1121, maxWeight: 1280, packageSize: 1728, fee: 11000, etaForSeller: "1 - 5 days", requiresDimensions: true },
  { id: 2482, name: "0.25 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 0, maxWeight: 4, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2483, name: "0.5 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 5, maxWeight: 8, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2484, name: "1 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 9, maxWeight: 16, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2485, name: "2 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 17, maxWeight: 32, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2486, name: "3 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 33, maxWeight: 48, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2487, name: "4 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 49, maxWeight: 64, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2488, name: "5 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 65, maxWeight: 80, packageSize: 1728, fee: 797, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2489, name: "6 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 81, maxWeight: 96, packageSize: 1728, fee: 1199, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2490, name: "7 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 97, maxWeight: 112, packageSize: 1728, fee: 1199, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2491, name: "8 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 113, maxWeight: 128, packageSize: 1728, fee: 1199, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2492, name: "9 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 129, maxWeight: 144, packageSize: 1728, fee: 1199, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2493, name: "10 lb", carrier: "fedex", handlingType: "smartpost", carrierDisplayName: "FedEx Ground Economy", requestClassDisplayName: "FedEx Ground Economy", minWeight: 145, maxWeight: 160, packageSize: 1728, fee: 1199, etaForSeller: "2 - 8 days", requiresDimensions: true },
  { id: 2494, name: "0.06 lb", carrier: "shippo_usps", handlingType: "first_class_envelope", carrierDisplayName: "USPS First-Class Envelope", requestClassDisplayName: "USPS First-Class Envelope", minWeight: 0, maxWeight: 1, packageSize: 17.609375, fee: 49, etaForSeller: "2 - 15 days", requiresDimensions: true },
  { id: 2495, name: "0.13 lb", carrier: "shippo_usps", handlingType: "first_class_envelope", carrierDisplayName: "USPS First-Class Envelope", requestClassDisplayName: "USPS First-Class Envelope", minWeight: 1, maxWeight: 2, packageSize: 17.609375, fee: 49, etaForSeller: "2 - 15 days", requiresDimensions: true },
  { id: 2496, name: "0.19 lb", carrier: "shippo_usps", handlingType: "first_class_envelope", carrierDisplayName: "USPS First-Class Envelope", requestClassDisplayName: "USPS First-Class Envelope", minWeight: 2, maxWeight: 3, packageSize: 17.609375, fee: 49, etaForSeller: "2 - 15 days", requiresDimensions: true },
  { id: 2507, name: "0.25 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 0, maxWeight: 4, packageSize: 3456, fee: 587, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2508, name: "0.5 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 5, maxWeight: 8, packageSize: 3456, fee: 641, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2509, name: "0.75 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 9, maxWeight: 12, packageSize: 3456, fee: 748, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2510, name: "1 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 13, maxWeight: 16, packageSize: 3456, fee: 812, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2511, name: "2 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 17, maxWeight: 32, packageSize: 3456, fee: 1443, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2512, name: "3 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 33, maxWeight: 48, packageSize: 3456, fee: 1604, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2513, name: "4 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 49, maxWeight: 64, packageSize: 3456, fee: 1711, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2514, name: "5 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 65, maxWeight: 80, packageSize: 3456, fee: 1818, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2515, name: "6 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 81, maxWeight: 96, packageSize: 3456, fee: 1925, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2516, name: "7 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 97, maxWeight: 112, packageSize: 3456, fee: 2032, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2517, name: "8 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 113, maxWeight: 128, packageSize: 3456, fee: 2139, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2518, name: "9 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 129, maxWeight: 144, packageSize: 3456, fee: 2246, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2519, name: "10 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 145, maxWeight: 160, packageSize: 3456, fee: 2353, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2520, name: "11 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 161, maxWeight: 176, packageSize: 3456, fee: 2781, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2521, name: "12 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 177, maxWeight: 192, packageSize: 3456, fee: 2889, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2522, name: "13 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 193, maxWeight: 208, packageSize: 3456, fee: 2996, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2523, name: "14 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 209, maxWeight: 224, packageSize: 3456, fee: 3103, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2524, name: "15 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 225, maxWeight: 240, packageSize: 3456, fee: 3210, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2525, name: "16 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 241, maxWeight: 256, packageSize: 3456, fee: 3317, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2526, name: "17 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 257, maxWeight: 272, packageSize: 3456, fee: 3424, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2527, name: "18 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 273, maxWeight: 288, packageSize: 3456, fee: 3531, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2528, name: "19 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 289, maxWeight: 304, packageSize: 3456, fee: 3745, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2529, name: "20 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 305, maxWeight: 320, packageSize: 3456, fee: 3852, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2530, name: "2 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 17, maxWeight: 32, packageSize: 3456, fee: 1743, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2531, name: "3 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 33, maxWeight: 48, packageSize: 3456, fee: 2021, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2532, name: "4 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 49, maxWeight: 64, packageSize: 3456, fee: 2455, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2533, name: "5 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 65, maxWeight: 80, packageSize: 3456, fee: 2621, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2534, name: "6 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 81, maxWeight: 96, packageSize: 3456, fee: 2883, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2535, name: "7 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 97, maxWeight: 112, packageSize: 3456, fee: 3145, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2536, name: "8 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 113, maxWeight: 128, packageSize: 3456, fee: 3424, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2537, name: "9 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 129, maxWeight: 144, packageSize: 3456, fee: 3681, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2538, name: "10 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 145, maxWeight: 160, packageSize: 3456, fee: 3970, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2539, name: "11 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 161, maxWeight: 176, packageSize: 3456, fee: 4269, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2540, name: "12 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 177, maxWeight: 192, packageSize: 3456, fee: 4558, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2541, name: "13 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 193, maxWeight: 208, packageSize: 3456, fee: 4842, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2542, name: "14 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 209, maxWeight: 224, packageSize: 3456, fee: 5147, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2543, name: "15 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 225, maxWeight: 240, packageSize: 3456, fee: 5399, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2544, name: "16 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 241, maxWeight: 256, packageSize: 3456, fee: 5677, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2545, name: "17 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 257, maxWeight: 272, packageSize: 3456, fee: 5987, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2546, name: "18 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 273, maxWeight: 288, packageSize: 3456, fee: 6314, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2547, name: "19 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 289, maxWeight: 304, packageSize: 3456, fee: 6619, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2548, name: "20 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 305, maxWeight: 320, packageSize: 3456, fee: 6956, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2549, name: "0.25 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 0, maxWeight: 4, packageSize: 1728, fee: 491, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2550, name: "0.5 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 5, maxWeight: 8, packageSize: 1728, fee: 566, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2552, name: "1 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 13, maxWeight: 16, packageSize: 1728, fee: 748, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2553, name: "2 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 17, maxWeight: 32, packageSize: 1728, fee: 1283, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2554, name: "3 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 33, maxWeight: 48, packageSize: 1728, fee: 1283, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2555, name: "4 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 49, maxWeight: 64, packageSize: 1728, fee: 1390, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2556, name: "5 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 65, maxWeight: 80, packageSize: 1728, fee: 1497, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2557, name: "6 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 81, maxWeight: 96, packageSize: 1728, fee: 1604, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2558, name: "7 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 97, maxWeight: 112, packageSize: 1728, fee: 1711, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2559, name: "8 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 113, maxWeight: 128, packageSize: 1728, fee: 1818, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2560, name: "9 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 129, maxWeight: 144, packageSize: 1728, fee: 1925, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2561, name: "10 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 145, maxWeight: 160, packageSize: 1728, fee: 2032, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2562, name: "11 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 161, maxWeight: 176, packageSize: 1728, fee: 2460, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2563, name: "12 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 177, maxWeight: 192, packageSize: 1728, fee: 2567, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2564, name: "13 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 193, maxWeight: 208, packageSize: 1728, fee: 2674, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2565, name: "14 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 209, maxWeight: 224, packageSize: 1728, fee: 2781, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2566, name: "15 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 225, maxWeight: 240, packageSize: 1728, fee: 2889, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2567, name: "16 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 241, maxWeight: 256, packageSize: 1728, fee: 2996, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2568, name: "17 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 257, maxWeight: 272, packageSize: 1728, fee: 3103, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2569, name: "18 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 273, maxWeight: 288, packageSize: 1728, fee: 3210, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2570, name: "19 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 289, maxWeight: 304, packageSize: 1728, fee: 3424, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2571, name: "20 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Ground Advantage", requestClassDisplayName: "USPS Ground Advantage", minWeight: 305, maxWeight: 320, packageSize: 1728, fee: 3531, etaForSeller: "1 - 7 days", requiresDimensions: false },
  { id: 2572, name: "2 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 17, maxWeight: 32, packageSize: 1728, fee: 1529, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2573, name: "3 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 33, maxWeight: 48, packageSize: 1728, fee: 1925, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2574, name: "4 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 49, maxWeight: 64, packageSize: 1728, fee: 2246, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2575, name: "5 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 65, maxWeight: 80, packageSize: 1728, fee: 2460, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2576, name: "6 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 81, maxWeight: 96, packageSize: 1728, fee: 2781, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2577, name: "7 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 97, maxWeight: 112, packageSize: 1728, fee: 2996, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2578, name: "8 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 113, maxWeight: 128, packageSize: 1728, fee: 3317, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2579, name: "9 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 129, maxWeight: 144, packageSize: 1728, fee: 3531, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2580, name: "10 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 145, maxWeight: 160, packageSize: 1728, fee: 3852, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2581, name: "11 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 161, maxWeight: 176, packageSize: 1728, fee: 4066, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2582, name: "12 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 177, maxWeight: 192, packageSize: 1728, fee: 4280, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2583, name: "13 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 193, maxWeight: 208, packageSize: 1728, fee: 4601, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2584, name: "14 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 209, maxWeight: 224, packageSize: 1728, fee: 4922, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2585, name: "15 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 225, maxWeight: 240, packageSize: 1728, fee: 5136, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2586, name: "16 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 241, maxWeight: 256, packageSize: 1728, fee: 5350, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2587, name: "17 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 257, maxWeight: 272, packageSize: 1728, fee: 5457, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2588, name: "18 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 273, maxWeight: 288, packageSize: 1728, fee: 5886, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2589, name: "19 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 289, maxWeight: 304, packageSize: 1728, fee: 5993, etaForSeller: "1 - 5 days", requiresDimensions: false },
  { id: 2590, name: "20 lb", carrier: "shippo_usps", handlingType: "standard", carrierDisplayName: "USPS Priority Mail", requestClassDisplayName: "USPS Priority Mail", minWeight: 305, maxWeight: 320, packageSize: 1728, fee: 6314, etaForSeller: "1 - 5 days", requiresDimensions: false },
];

// weightOz — package weight in ounces
// volumeCuIn — L × W × H in cubic inches (pass 0 if no dimensions)
export function getStaticShippingClasses(
  weightOz: number,
  volumeCuIn: number
): ShippingClass[] {
  const carrierPool: Array<[string, string]> = [
    ["shippo_usps", "standard"],
    ["fedex", "standard"],
    ["fedex", "smartpost"],
    ["ups", "standard"],
    ["ups", "surepost"],
  ];

  const results: ShippingClass[] = [];

  for (const [carrier, handlingType] of carrierPool) {
    const tiers = shippingCarriers.filter(
      (s) => s.carrier === carrier && s.handlingType === handlingType
    );

    // Prefer a tier where weight falls within the stated min–max AND volume fits.
    const exactFit = tiers.find(
      (t) =>
        weightOz >= t.minWeight &&
        weightOz <= t.maxWeight &&
        (volumeCuIn === 0 || volumeCuIn <= t.packageSize)
    );

    // Fallback: any tier whose max weight covers the package (ignores min).
    const maxFit = tiers.find(
      (t) =>
        weightOz <= t.maxWeight &&
        (volumeCuIn === 0 || volumeCuIn <= t.packageSize)
    );

    if (exactFit && maxFit && exactFit.id !== maxFit.id) {
      results.push(exactFit, maxFit);
    } else if (exactFit) {
      results.push(exactFit);
    } else if (maxFit) {
      results.push(maxFit);
    }
  }

  return results;
}
